server:
  port: 9191
api:
  prefix: api/v1

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/job_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true